baseURL: "https://leovan.me/"
languageCode: "en-us"
title: "Leo Van | 范叶亮"
theme: "hugo-ivy"
googleAnalytics: "UA-48667916-2"
disqusShortname: "leovan"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$", 
              "\\.txt$", "\\.csv$", "\\.tsv$",
              "\\.tgz$", "\\.tar$", "\\.gz$", "\\.zip$", "\\.npz$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 30

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "关于"
      url: "/cn/about/"
      weight: 1
    - name: "博客"
      url: "/cn/"
      weight: 2
    - name: "About"
      url: "/en/about/"
      weight: 3
    - name: "Blog"
      url: "/en/"
      weight: 4
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "Categories"
      url: "/categories/"
      weight: 3
    - name: "Tags"
      url: "/tags/"
      weight: 4
    - identifier: "en-menu-separator-1"
      url: "#menu-separator"
      weight: 5
    - name: "About"
      url: "/en/about/"
      weight: 6
    - name: "Resume"
      url: "/en/resume/"
      weight: 7
    - identifier: "en-menu-separator-2"
      url: "#menu-separator"
      weight: 8
    - name: "中文"
      url: "/cn/"
      weight: 9
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "博客"
      url: "/cn/"
      weight: 2
    - name: "分类"
      url: "/categories/"
      weight: 3
    - name: "标签"
      url: "/tags/"
      weight: 4
    - identifier: "cn-menu-separator-1"
      url: "#menu-separator"
      weight: 5
    - name: "关于"
      url: "/cn/about/"
      weight: 6
    - name: "简历"
      url: "/cn/resume/"
      weight: 7
    - identifier: "cn-menu-separator-2"
      url: "#menu-separator"
      weight: 8
    - name: "English"
      url: "/en/"
      weight: 9

params:
  description: "Personal website of Leo Van; 范叶亮的个人网站"
  footer: "&copy; [Leo Van](/) 2017 - 2018 | [Github](https://github.com/leovan) | [ORCID](https://orcid.org/0000-0002-9556-7821) | I am Mr. Black"
  disqusURL: "https://leovan.me"
  customJS: ["js/fix-toc.js", "js/center-img.js", "js/right-quote.js", "js/fix-footnote.js", "js/math-code.js"]
  googleAdsense: "ca-pub-2608165017777396"
  
  prismjsVersion: "1.15.0"
  prismjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  prismjsLang: ["r", "python", "markup", "yaml", "latex", "bash", "powershell", "javascript"]
  prismjsTheme: ""
  prismjsPlugin: ["show-language"]
  
  mathjaxVersion: "2.7.5"
  mathjaxCDN: "//cdnjs.cloudflare.com/ajax/libs"
  
  katexVersion: "0.10.0"
  katexCDN: "//cdnjs.cloudflare.com/ajax/libs"
  
  pseudocodeVersion: "latest"
  pseudocodeCDN: "//cdn.leovan.me/libraries"
  
  jQueryVersion: "3.3.1"
  jQueryCDN: "//cdnjs.cloudflare.com/ajax/libs"
  
  photoswipeVersion: "4.1.2"
  photoswipeCDN: "//cdnjs.cloudflare.com/ajax/libs"
  
  videojsVersion: "7.3.0"
  videojsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  
  materialDesignIconsVersion: "3.0.1"
  materialDesignIconsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  
  panguVersion: "3.3.0"
  panguCDN: "//cdnjs.cloudflare.com/ajax/libs"
  
  materialComponentsWebVersion: "latest"
  materialComponentsWebCDN: "//unpkg.com"

  logo:
    img: "/images/avatar.svg"
    url: "/"
    alt: "Mr. Black"
    tag: "Soldier to Solider"

  author:
    en: "Leo Van"
    cn: "范叶亮"

  lang:
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"
    categories:
      cn: "分类"
      en: "Categories"
    tags:
      cn: "标签"
      en: "Tags"
    wordcount:
      cn: "字数"
      en: "Word Count"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false
    hrefTargetBlank: true
