baseurl: "https://leovan.me/"
languageCode: "en-us"
title: "Leo | 范叶亮"
theme: "hugo-ivy"
googleAnalytics: "UA-48667916-2"
disqusShortname: "leovan"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 30

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "关于"
      url: "/cn/about/"
      weight: 3
    - name: "博客"
      url: "/cn/"
      weight: 4
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: ""
      url: ""
      weight: 4
    - name: "Categories"
      url: "/categories/"
      weight: 5
    - name: "Tags"
      url: "/tags/"
      weight: 6
    - name: " "
      url: ""
      weight: 7
    - name: "中文"
      url: "/cn/"
      weight: 8
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "博客"
      url: "/cn/"
      weight: 3
    - name: "书籍"
      url: "/cn/books/"
      weight: 4
    - name: "音乐"
      url: "/categories/音乐/"
      weight: 5
    - name: "电影"
      url: "/categories/电影/"
      weight: 6
    - name: "旅行"
      url: "/categories/旅行/"
      weight: 7
    - name: "摄影"
      url: "/categories/摄影/"
      weight: 8
    - name: ""
      url: ""
      weight: 9
    - name: "分类"
      url: "/categories/"
      weight: 10
    - name: "标签"
      url: "/tags/"
      weight: 11
    - name: " "
      url: ""
      weight: 12
    - name: "English"
      url: "/en/"
      weight: 13

params:
  description: "Personal website of Leo Van; 范叶亮的个人网站"
  footer: "&copy; [Leo Van](/) 2017 - 2017 | I am Mr. Black"
  disqusURL: "http://leovan.me"
  customJS: ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js"]
  
  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "python", "yaml", "tex"]
  highlightjsTheme: "atom-one-light"
  
  # options for KaTeX (for pseudocode.js)
  katexVersion: "0.8.3"
  katexCDN: "//cdn.bootcss.com"
  
  # options for jQuery
  jQueryVersion: "3.2.1"
  jQueryCDN: "//cdn.bootcss.com"
  
  # options for photoswipe
  photoswipeVersion: "4.1.2"
  photoswipeCDN: "//cdn.bootcss.com"

  logo:
    img: "/images/icons/gravatar.png"
    url: "/"
    alt: "Mr. Black"
    tag: "Soldier to Solider"

  author:
    en: "Leo Van"
    cn: "范叶亮"

  lang:
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"
    categories:
      cn: "分类"
      en: "Categories"
    tags:
      cn: "标签"
      en: "Tags"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false
